repos:
  - repo: local
    hooks:
      - id: lint-fix
        name: ruff lint + format
        entry: task lint:fix
        language: system
        types: [python]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: task typecheck
        language: system
        types: [python]
        pass_filenames: false
