#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DIST_DIR="$REPO_ROOT/dist"

# ── Colors ───────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── Prompt helper ────────────────────────────────────────
prompt() {
    local var_name="$1" prompt_text="$2" default="$3"
    local input
    if [[ -n "$default" ]]; then
        read -rp "$(echo -e "${CYAN}$prompt_text${NC} [${default}]: ")" input
        printf -v "$var_name" '%s' "${input:-$default}"
    else
        while true; do
            read -rp "$(echo -e "${CYAN}$prompt_text${NC}: ")" input
            if [[ -n "$input" ]]; then
                printf -v "$var_name" '%s' "$input"
                break
            fi
            error "This field is required"
        done
    fi
}

prompt_optional() {
    local var_name="$1" prompt_text="$2"
    local input
    read -rp "$(echo -e "${CYAN}$prompt_text${NC}: ")" input
    printf -v "$var_name" '%s' "$input"
}

gen_secret() {
    openssl rand -base64 "$1" 2>/dev/null | tr -d '\n'
}

# ── Collect configuration ────────────────────────────────
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Rental Platform — Production Setup${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════${NC}"
echo ""

info "Domain & access"
prompt DOMAIN        "Domain name (e.g. equip-me.ru)" ""
prompt LETSENCRYPT_EMAIL "Let's Encrypt email" ""
prompt APP_VERSION   "App version to deploy" ""
prompt VM_HOST       "VM address (user@host)" ""

echo ""
info "Database"
prompt POSTGRES_USER "PostgreSQL user" "rental"
prompt POSTGRES_DB   "PostgreSQL database" "rental"
prompt POSTGRES_PASSWORD "PostgreSQL password" "$(gen_secret 32)"

echo ""
info "Authentication"
prompt JWT_SECRET "JWT secret key" "$(gen_secret 48)"

echo ""
info "Object storage (MinIO)"
prompt MINIO_ROOT_USER     "MinIO root user" "minioadmin"
prompt MINIO_ROOT_PASSWORD "MinIO root password" "$(gen_secret 32)"

echo ""
info "Monitoring"
prompt GRAFANA_ADMIN_PASSWORD "Grafana admin password" "$(gen_secret 16)"

echo ""
info "External services"
prompt_optional DADATA_API_KEY "Dadata API key (optional, press Enter to skip)"

# ── Computed values ──────────────────────────────────────
API_HOST="api.${DOMAIN}"
GRAFANA_HOST="grafana.${DOMAIN}"
S3_HOST="s3.${DOMAIN}"
STORAGE__PRESIGNED_ENDPOINT_URL="https://${S3_HOST}"
CORS__ALLOW_ORIGINS="[\"https://${DOMAIN}\",\"https://www.${DOMAIN}\"]"

# ── Build dist/ ──────────────────────────────────────────
info "Building dist/ directory..."

rm -rf "$DIST_DIR"
mkdir -p "$DIST_DIR"

cp "$SCRIPT_DIR/docker-compose.yml" "$DIST_DIR/"
cp -r "$SCRIPT_DIR/config" "$DIST_DIR/"

cat > "$DIST_DIR/.env" <<EOF
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Domain
DOMAIN=${DOMAIN}
API_HOST=${API_HOST}
GRAFANA_HOST=${GRAFANA_HOST}
S3_HOST=${S3_HOST}
LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

# App
APP_VERSION=${APP_VERSION}

# Database
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Auth
JWT_SECRET=${JWT_SECRET}

# Storage
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
STORAGE__PRESIGNED_ENDPOINT_URL=${STORAGE__PRESIGNED_ENDPOINT_URL}

# CORS
CORS__ALLOW_ORIGINS=${CORS__ALLOW_ORIGINS}

# Grafana
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

# External
DADATA_API_KEY=${DADATA_API_KEY}

# Deployment
VM_HOST=${VM_HOST}
EOF

ok "dist/ directory ready"

# ── Deploy to VM ─────────────────────────────────────────
echo ""
info "Deploying to ${VM_HOST}..."

ssh "$VM_HOST" "mkdir -p ~/rental-platform"
scp -r "$DIST_DIR/." "$VM_HOST:~/rental-platform/"

ok "Files copied to ${VM_HOST}:~/rental-platform/"

info "Starting services..."
ssh "$VM_HOST" "cd ~/rental-platform && docker compose pull && docker compose up -d"

# ── Summary ──────────────────────────────────────────────
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Deployment complete!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════${NC}"
echo ""
echo -e "  API:     ${CYAN}https://${API_HOST}${NC}"
echo -e "  Grafana: ${CYAN}https://${GRAFANA_HOST}${NC}"
echo -e "  S3:      ${CYAN}https://${S3_HOST}${NC}"
echo ""
echo -e "  Grafana login: admin / ${GRAFANA_ADMIN_PASSWORD}"
echo ""
info "TLS certificates will be provisioned automatically by Let's Encrypt."
info "Ensure DNS A records point to the VM for: ${API_HOST}, ${GRAFANA_HOST}, ${S3_HOST}"
echo ""
