#!/usr/bin/env bash
set -euo pipefail

# ── Rental Platform — production bootstrap ──────────────────────────
# Run on a clean VM to set up the entire stack via docker compose.
#
# Usage:
#   ./scripts/init-prod.sh              # interactive — prompts for values
#   ./scripts/init-prod.sh --defaults   # non-interactive — generates all secrets
# ─────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_DIR/.env"
COMPOSE_FILE="$PROJECT_DIR/docker-compose.prod.yml"

# ── Defaults ────────────────────────────────────────────────────────

DEFAULT_APP_VERSION="0.4.0"
DEFAULT_POSTGRES_USER="rental"
DEFAULT_POSTGRES_DB="rental_prod"

# ── Helpers ─────────────────────────────────────────────────────────

gen_secret() {
  openssl rand -base64 "$1" | tr -d '/+=' | head -c "$1"
}

info()  { printf '\033[1;34m[INFO]\033[0m  %s\n' "$*"; }
warn()  { printf '\033[1;33m[WARN]\033[0m  %s\n' "$*"; }
error() { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }

# ── Prerequisites ───────────────────────────────────────────────────

check_prerequisites() {
  info "Checking prerequisites…"

  if ! command -v docker &>/dev/null; then
    error "docker is not installed. Install Docker Engine: https://docs.docker.com/engine/install/"
  fi

  if ! docker compose version &>/dev/null; then
    error "docker compose plugin is not available. Install it: https://docs.docker.com/compose/install/"
  fi

  if ! command -v openssl &>/dev/null; then
    error "openssl is not installed (needed for secret generation)."
  fi

  info "All prerequisites met."
}

# ── Prompt helper (falls back to default in --defaults mode) ────────

ask() {
  local var_name="$1" prompt="$2" default="$3" secret="${4:-false}"

  if [[ "${NON_INTERACTIVE:-false}" == "true" ]]; then
    printf -v "$var_name" '%s' "$default"
    return
  fi

  if [[ "$secret" == "true" ]]; then
    read -rsp "$prompt [$default]: " value
    echo
  else
    read -rp "$prompt [$default]: " value
  fi
  printf -v "$var_name" '%s' "${value:-$default}"
}

# ── Gather configuration ───────────────────────────────────────────

gather_config() {
  info "Configuring production environment…"

  ask APP_VERSION       "App image version"            "$DEFAULT_APP_VERSION"
  ask POSTGRES_USER     "PostgreSQL user"              "$DEFAULT_POSTGRES_USER"
  ask POSTGRES_PASSWORD "PostgreSQL password"           "$(gen_secret 32)" true
  ask POSTGRES_DB       "PostgreSQL database"           "$DEFAULT_POSTGRES_DB"
  ask JWT_SECRET        "JWT signing secret"            "$(gen_secret 48)" true
  ask MINIO_ROOT_USER   "MinIO root user"              "minioadmin"
  ask MINIO_ROOT_PASSWORD "MinIO root password"         "$(gen_secret 32)" true
  ask CLICKHOUSE_PASSWORD "ClickHouse password"         "$(gen_secret 24)" true
  ask GRAFANA_ADMIN_PASSWORD "Grafana admin password"   "$(gen_secret 24)" true
  ask DADATA_API_KEY    "Dadata API key (optional)"     ""
}

# ── Write .env ──────────────────────────────────────────────────────

write_env() {
  if [[ -f "$ENV_FILE" ]]; then
    warn ".env already exists — backing up to .env.bak"
    cp "$ENV_FILE" "$ENV_FILE.bak"
  fi

  cat > "$ENV_FILE" <<EOF
# Generated by init-prod.sh on $(date -Iseconds)
# ── App ──
APP_VERSION=${APP_VERSION}

# ── PostgreSQL ──
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}

# ── JWT ──
JWT_SECRET=${JWT_SECRET}

# ── MinIO (S3) ──
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

# ── ClickHouse ──
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}

# ── Grafana ──
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

# ── External APIs ──
DADATA_API_KEY=${DADATA_API_KEY}
EOF

  chmod 600 "$ENV_FILE"
  info ".env written (mode 600)."
}

# ── Pull images ─────────────────────────────────────────────────────

pull_images() {
  info "Pulling application image…"
  docker pull "ghcr.io/khamitovdr/rental-platform:${APP_VERSION}"

  info "Pulling infrastructure images…"
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" pull
}

# ── Run migrations ──────────────────────────────────────────────────

run_migrations() {
  info "Starting database…"
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d db
  info "Waiting for database to be healthy…"
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up --wait db

  info "Running migrations…"
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" run --rm migrate
}

# ── Start services ──────────────────────────────────────────────────

start_services() {
  info "Starting all services…"
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d

  info "Waiting for services to be ready…"
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" ps
}

# ── Main ────────────────────────────────────────────────────────────

main() {
  if [[ "${1:-}" == "--defaults" ]]; then
    NON_INTERACTIVE=true
  fi

  cd "$PROJECT_DIR"

  check_prerequisites
  gather_config
  write_env
  pull_images
  run_migrations
  start_services

  echo
  info "Production stack is running!"
  echo
  echo "  App:      http://localhost:8000"
  echo "  Grafana:  http://localhost:3001  (admin / <your password>)"
  echo
  echo "  Logs:     docker compose -f docker-compose.prod.yml logs -f"
  echo "  Stop:     docker compose -f docker-compose.prod.yml down"
  echo
}

main "$@"
